[package]
name = "anti-distraction_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
opencv = { version = "0.92.2", features = ["clang-runtime", "highgui", "videoio", "imgcodecs", "imgproc"] }
rodio = "0.19.0"
